### ISSUE TITLE
Improve error handling for reports not specified in DB

### ISSUE THREAD

**Issue by Nunie123** [speedyturkey/porthole#48]
Currently, when attempting to run a report that does not have a record in the `automated_reports` table porthole gives the following errors:
`IndexError: list index out of range` and `Exception: Report [report_name] does not exist`.

A more useful error message might be "Exception: Report [report_name] was not found in the `automated_reports` table.  Please ensure the `report_name` specified in this file matches a record in the `automated_reports` table."

**Comment by speedyturkey** [comment]
Resolved by PR #49.
